version: 1
services:
  - type: web
    name: music-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    dockerfilePath: Dockerfile
    envVars:
      - key: FF_PATH
        value: /usr/bin/ffmpeg
