version: 1
services:
  - type: web
    name: music-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: docker build -t music-server .
    startCommand: docker run -p $PORT:3000 music-server
